name: myanimelist
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  build_runner: ^2.1.7
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.1
  http: ^0.13.5
  image: ^4.0.13
  intl: ^0.17.0
  json_annotation: ^4.8.0
  pkce: ^1.1.0+1
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
